# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80abc81440b4da9fc5c4b34bf476b485e07df7935784e1446c884393aadc3eba0ca8da8c1c5609ba6b97e137bab9391fbec5ca17e4b6c3c9e742753e542e92f8

test:
  secret_key_base: db6d6669ec674414c83b1c7215bab259e064a371ca57bf73255b63e1b1a04c74ef3a6033ca6ddb79d016f8fe0907bd5f5206ac1d64361a713563d030e38475a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
